theme: jekyll-theme-architect

navbar-links:
  Main: "README.md"
  Modules:
    - Main: "modules/README.md"
    - Learn markdown: "https://www.markdowntutorial.com/"
  Author's home: "https://deanattali.com"